version: "3"

services:
  # Golang.
  server:
    build:
      context: .
      dockerfile: ./build/docker/server/Dockerfile
    container_name: server
    ports:
      - 8080:8080
    # env_file: local_env.sh
    entrypoint: ["./server", "server"]
    networks:
      - private-network
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: library_dev
    ports:
     - "3306:3306"
    networks:
      - private-network

  redis:
    image: redis:3.2.4-alpine
    ports:
      - "6389:6379"
    networks:
      - private-network
  swagger:
    build:
      context: .
      dockerfile: ./build/docker/swagger/Dockerfile
    ports:
      - 3000:8080
    networks:
      - private-network

networks:
  private-network:
    driver: bridge
